//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveWPFApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveWPFApp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +.
        /// </summary>
        public static string MainWindow_AddSaveTaskButtonText {
            get {
                return ResourceManager.GetString("MainWindow_AddSaveTaskButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string MainWindow_DeleteButtonText {
            get {
                return ResourceManager.GetString("MainWindow_DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string MainWindow_ModifySaveTaskButtonText {
            get {
                return ResourceManager.GetString("MainWindow_ModifySaveTaskButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string MainWindow_NameColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_NameColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner.
        /// </summary>
        public static string MainWindow_SelectColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_SelectColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string MainWindow_SettingsButtonText {
            get {
                return ResourceManager.GetString("MainWindow_SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string MainWindow_SourceColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_SourceColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrer la sélection.
        /// </summary>
        public static string MainWindow_StartSelectionButtonText {
            get {
                return ResourceManager.GetString("MainWindow_StartSelectionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination.
        /// </summary>
        public static string MainWindow_TargetColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_TargetColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string MainWindow_TypeColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_TypeColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string SettingsMenu_CancelButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions à crypter :.
        /// </summary>
        public static string SettingsMenu_EncryptingExtensionText {
            get {
                return ResourceManager.GetString("SettingsMenu_EncryptingExtensionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anglais.
        /// </summary>
        public static string SettingsMenu_EnglishButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_EnglishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez une extension à rajouter à la liste.
        /// </summary>
        public static string SettingsMenu_EnterExtensionPromptText {
            get {
                return ResourceManager.GetString("SettingsMenu_EnterExtensionPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer.
        /// </summary>
        public static string SettingsMenu_ExtensionsValidateButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_ExtensionsValidateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        public static string SettingsMenu_FrenchButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_FrenchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON.
        /// </summary>
        public static string SettingsMenu_JsonRadioButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_JsonRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue.
        /// </summary>
        public static string SettingsMenu_LanguageText {
            get {
                return ResourceManager.GetString("SettingsMenu_LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log formats.
        /// </summary>
        public static string SettingsMenu_LogFormatText {
            get {
                return ResourceManager.GetString("SettingsMenu_LogFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder.
        /// </summary>
        public static string SettingsMenu_SaveButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string SettingsMenu_Title {
            get {
                return ResourceManager.GetString("SettingsMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML.
        /// </summary>
        public static string SettingsMenu_XmlRadioButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_XmlRadioButtonText", resourceCulture);
            }
        }
    }
}
