//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveWPFApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveWPFApp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string MainWindow_AddSaveTaskButtonText {
            get {
                return ResourceManager.GetString("MainWindow_AddSaveTaskButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string MainWindow_DeleteButtonText {
            get {
                return ResourceManager.GetString("MainWindow_DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echanger le type.
        /// </summary>
        public static string MainWindow_ModifySaveTaskButtonText {
            get {
                return ResourceManager.GetString("MainWindow_ModifySaveTaskButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string MainWindow_NameColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_NameColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner.
        /// </summary>
        public static string MainWindow_SelectColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_SelectColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MainWindow_SettingsButtonText {
            get {
                return ResourceManager.GetString("MainWindow_SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string MainWindow_SourceColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_SourceColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer la sélection.
        /// </summary>
        public static string MainWindow_StartSelectionButtonText {
            get {
                return ResourceManager.GetString("MainWindow_StartSelectionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string MainWindow_TargetColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_TargetColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MainWindow_TypeColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_TypeColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string SaveTask_StateActive {
            get {
                return ResourceManager.GetString("SaveTask_StateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finie.
        /// </summary>
        public static string SaveTask_StateEnd {
            get {
                return ResourceManager.GetString("SaveTask_StateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string SaveTask_StateError {
            get {
                return ResourceManager.GetString("SaveTask_StateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etat invalide.
        /// </summary>
        public static string SaveTask_StateINVALID {
            get {
                return ResourceManager.GetString("SaveTask_StateINVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En pause.
        /// </summary>
        public static string SaveTask_StatePaused {
            get {
                return ResourceManager.GetString("SaveTask_StatePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêtée.
        /// </summary>
        public static string SaveTask_StateStopped {
            get {
                return ResourceManager.GetString("SaveTask_StateStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre en pause la sélection.
        /// </summary>
        public static string SaveTaskProgress_PauseSelectedButton {
            get {
                return ResourceManager.GetString("SaveTaskProgress_PauseSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommencer la sélection.
        /// </summary>
        public static string SaveTaskProgress_PlaySelectedButton {
            get {
                return ResourceManager.GetString("SaveTaskProgress_PlaySelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progression.
        /// </summary>
        public static string SaveTaskProgress_ProgressColumnTitle {
            get {
                return ResourceManager.GetString("SaveTaskProgress_ProgressColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etat.
        /// </summary>
        public static string SaveTaskProgress_StateColumnTitle {
            get {
                return ResourceManager.GetString("SaveTaskProgress_StateColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopper la sélection.
        /// </summary>
        public static string SaveTaskProgress_StopSelectedButton {
            get {
                return ResourceManager.GetString("SaveTaskProgress_StopSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travail(s) de sauvegarde en cours.
        /// </summary>
        public static string SaveTaskProgress_Title {
            get {
                return ResourceManager.GetString("SaveTaskProgress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string SettingsMenu_CancelButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions à crypter :.
        /// </summary>
        public static string SettingsMenu_EncryptingExtensionText {
            get {
                return ResourceManager.GetString("SettingsMenu_EncryptingExtensionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglais.
        /// </summary>
        public static string SettingsMenu_EnglishButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_EnglishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez une extension à rajouter à la liste.
        /// </summary>
        public static string SettingsMenu_EnterExtensionPromptText {
            get {
                return ResourceManager.GetString("SettingsMenu_EnterExtensionPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer.
        /// </summary>
        public static string SettingsMenu_ExtensionsValidateButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_ExtensionsValidateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string SettingsMenu_FrenchButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_FrenchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string SettingsMenu_JsonRadioButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_JsonRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string SettingsMenu_LanguageText {
            get {
                return ResourceManager.GetString("SettingsMenu_LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log formats.
        /// </summary>
        public static string SettingsMenu_LogFormatText {
            get {
                return ResourceManager.GetString("SettingsMenu_LogFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string SettingsMenu_SaveButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string SettingsMenu_Title {
            get {
                return ResourceManager.GetString("SettingsMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        public static string SettingsMenu_XmlRadioButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_XmlRadioButtonText", resourceCulture);
            }
        }
    }
}
