//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveWPFApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveWPFApp.Resources.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string MainWindow_AddSaveTaskButtonText {
            get {
                return ResourceManager.GetString("MainWindow_AddSaveTaskButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string MainWindow_DeleteButtonText {
            get {
                return ResourceManager.GetString("MainWindow_DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        internal static string MainWindow_ModifySaveTaskButtonText {
            get {
                return ResourceManager.GetString("MainWindow_ModifySaveTaskButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nom.
        /// </summary>
        internal static string MainWindow_NameColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_NameColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner.
        /// </summary>
        internal static string MainWindow_SelectColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_SelectColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string MainWindow_SettingsButtonText {
            get {
                return ResourceManager.GetString("MainWindow_SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string MainWindow_SourceColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_SourceColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer la sélection.
        /// </summary>
        internal static string MainWindow_StartSelectionButtonText {
            get {
                return ResourceManager.GetString("MainWindow_StartSelectionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string MainWindow_TargetColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_TargetColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string MainWindow_TypeColumnTitle {
            get {
                return ResourceManager.GetString("MainWindow_TypeColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string SettingsMenu_CancelButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions à crypter.
        /// </summary>
        internal static string SettingsMenu_EncryptingExtensionText {
            get {
                return ResourceManager.GetString("SettingsMenu_EncryptingExtensionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez une extension à rajouter à la liste.
        /// </summary>
        internal static string SettingsMenu_EnterExtensionPromptText {
            get {
                return ResourceManager.GetString("SettingsMenu_EnterExtensionPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        internal static string SettingsMenu_ExtensionsValidateButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_ExtensionsValidateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string SettingsMenu_JsonRadioButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_JsonRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        internal static string SettingsMenu_LanguageText {
            get {
                return ResourceManager.GetString("SettingsMenu_LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format des logs.
        /// </summary>
        internal static string SettingsMenu_LogFormatText {
            get {
                return ResourceManager.GetString("SettingsMenu_LogFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string SettingsMenu_SaveButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string SettingsMenu_Title {
            get {
                return ResourceManager.GetString("SettingsMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string SettingsMenu_XmlRadioButtonText {
            get {
                return ResourceManager.GetString("SettingsMenu_XmlRadioButtonText", resourceCulture);
            }
        }
    }
}
