@startuml

/' ==================== Packages ==================== '/
package "Model" {
    class SaveTaskFactory {
        ~ CreateSave(saveTaskTypes: ESaveTaskTypes, sourcePath: string, targetPath: string): SaveTask
    }

abstract class SaveTask {
        - DirectoryPair CurrentDirectoryPair
        - bool isSoftwareRunning
        - bool IsSaveSuccessful
        - LogRealTime logRealTime
        - LogDaily logDaily
        - List<string> UnsavedPaths
        - string name
        + string BindName
        + string BindSource
        + string BindDestination
        + ESaveTaskTypes BindSaveTaskType
        + void SetLogRealTime(LogRealTime logRealTime)
        + void SetLogDaily(LogDaily logDaily)
        + List<string> GetUnsavedPaths()
        + DirectoryPair GetDirectoryPair()
        + string GetMessageSaveTaskType()
        + ESaveTaskTypes GetSaveTaskType()
        + bool Save(SaveTaskManager saveTaskManager)
        + void CopySingleFile(string sourcePath, string targetPath, SaveTaskManager saveTaskManager)
        + void NotifySoftwareRunning(bool isSoftwareRunning)
        + void OnPropertyChanged(string propertyName)
    }

    class SaveTaskDifferential {
        - SaveDifferentialRecursive(string SourcePath, string TargetPath, SaveTaskManager saveTaskManager) : List<string>
        + SaveTaskDifferential(DirectoryPair CurrentDirectoryPair, string name)
        + SaveTaskDifferential(DirectoryPair CurrentDirectoryPair, LogDaily logDaily, LogRealTime logRealTime, string SaveTaskName)
        + Save(SaveTaskManager saveTaskManager) : bool
        + GetMessageSaveTaskType() : string
        + GetSaveTaskType() : ESaveTaskTypes
    }

    class SaveTaskComplete {
        - DirectoryPair CurrentDirectoryPair
        - bool isSoftwareRunning
        - bool IsSaveSuccessful
        - LogRealTime logRealTime
        - LogDaily logDaily
        - List<string> UnsavedPaths
        - string name
        + SaveTaskComplete(DirectoryPair CurrentDirectoryPair, string name)
        + SaveTaskComplete(DirectoryPair CurrentDirectoryPair, LogDaily logDaily, LogRealTime logRealTime, string saveTaskName)
        + bool Save(SaveTaskManager saveTaskManager)
        + string GetMessageSaveTaskType()
        + ESaveTaskTypes GetSaveTaskType()
    }

    class DirectoryPair {
        ~ SourcePath: string
        ~ TargetPath: string
        ~ DirectoryPair(SourcePath: string, TargetPath: string)
    }

    enum ESaveTaskTypes <<enum>> {
        Differential
        Complete
        Unknown
    }

    class ESaveTaskTypesExtension {
        {static} + Dictionary<ESaveTaskTypes, String> SaveTaskTypesStrings
        --
        {static} + List<String> GetAllStrSaveTasksType()
        {static} + ESaveTaskTypes ToESaveTaskTypes(String ESaveTaskTypesStr)
    }

class SaveTaskManager {
    - SaveTaskFactory : SaveTaskFactory
    - SaveTasks : ObservableCollection<SaveTask>
    - EncryptingExtensions : List<string>
    - CurrentUnsavedPaths : List<string>
    - processMonitor : ProcessMonitor
    - isSoftwareRunning : bool
    + SaveTaskManager()
    + OnSoftwareStatusChanged(isRunning : bool)
    + IsSaveTaskNameExist(name : string) : bool
    + GetSaveTaskByName(Name : string) : SaveTask
    + AddSaveTask(SaveTaskType : ESaveTaskTypes, sourcePath : string, targetPath : string, saveTaskName : string) : bool
    + RemoveSaveTask(name : string) : bool
    + ExecuteSaveTask(name : string) : bool
    + ModifySaveTaskType(name : string, newSaveTaskType : ESaveTaskTypes) : bool
    + ModifySaveTaskSourcePath(name : string, newSourcePath : string) : bool
    + ModifySaveTaskTargetPath(name : string, newTargetPath : string) : bool
    + ModifySaveTaskName(name : string, newName : string) : bool
    + SwitchSaveTask(name : string) : bool
    + SerializeSaveTasks()
    + SetEncryptingExtensions(newEncryptingExtensions : List<string>)
    + SerializeEncryptingExtensions()
    + DeserializeEncryptingExtensions()
}

interface ESaveTaskObserver {
    +void NotifySoftwareRunning(bool isSoftwareRunning)
}


class ProcessMonitor {
  -System.Timers.Timer timer
  -const string businessSoftware
  -bool isSoftwareRunning
  +event Action<bool> OnSoftwareStatusChanged
  +ProcessMonitor()
  -Task CheckBusinessSoftware()
  +void Stop()
}

class JsonManager {
    - string AppSettingsPath
    - string SaveTaskSerializationPath
    - string LogPathDaily
    - string LogPathRealTime
    - string EncryptingExtensionsSerializationPath
    - string EncryptionKey

    + string GetSettings(string settings)
    + void SerializeSaveTasks(ObservableCollection<SaveTask> SaveTasks)
    + List<SaveTask> DeserializeSaveTasks()
    + void SerializeEncryptingExtensions(List<string> EncryptingExtensions)
    + List<string> DeserializeEncryptingExtensions()
}

    class Utilities {
    + IsValidPath(path: string): bool
    }

    ' enum EMessage <<enum>> {
    '     ErrorTranslate
    '     InitMessage
    '     LanguagesMessage
    '     StopMessage
    '     StartSaveTaskMessage
    '     LanguageChangeSuccessMessage
    '     CreateSaveTaskMessage
    '     DefaultLanguageInitSuccessMessage
    '     DefaultLanguageInitErrorMessage
    '     DefaultLanguageChangedSuccessMessage
    '     DefaultLanguageChangedErrorMessage
    '     AskLanguageMessage
    '     ErrorUserEntryStrMessage
    '     ErrorUserEntryOptionMessage
    '     SaveTaskMenuMessage
    ' }

    ' class MessageExtensions {
    '     ~ static Dictionary<EMessage, string> MessageStrings
    '     ~ static string GetValue(EMessage message)
    ' }

    ' class MessageManager {
    '     ~ LanguageManager languageManager
    '     ~ JsonManager jsonManager
    '     + MessageManager(LanguageManager languageManager, JsonManager jsonManager)
    '     + string GetMessageTranslate(EMessage message)
    ' }


    /' Relations '/
    SaveTaskFactory --> SaveTask : "<<creates>>"
    SaveTask *--> DirectoryPair : "<<instanciates>>"
    SaveTask <|--- SaveTaskDifferential : "<<inherits>>"
    SaveTask <|--- SaveTaskComplete : "<<inherits>>"
    SaveTask --|> ESaveTaskObserver : "<<inherits>>"
    SaveTask --> ProcessMonitor : "<<Observe>>"
    SaveTaskManager o--> SaveTask : "<<contains>>"
    ESaveTaskTypes <-- SaveTaskFactory : "<<uses>>"
    SaveTaskFactory --> DirectoryPair : "<<creates>>"
    SaveTaskManager *--> ProcessMonitor : "<<instanciates>>"

    ' EMessage <-- MessageExtensions : "<<uses>>"
    ' MessageManager --> MessageExtensions : "<<uses>>"
}

package "ViewModel" {

    class SaveTaskViewModel {
    +SaveTaskManager saveTaskManager
    +List<String> EcliSaveTaskTypesStr
    +ObservableCollection<SaveTask> BindSaveTasks
    +CreateSaveTask(string saveTaskName, string saveTaskSource, string saveTaskTarget, ESaveTaskTypes saveTaskType)
    +ExecuteSaveTask(string name)
    +RemoveSaveTask(string name)
    +SwitchSaveTaskType(string name)
    +ModifySaveTaskSourcePath(string name, string path)
    +ModifySaveTaskTargetPath(string name, string path)
    +ModifySaveTaskName(string currentName, string newName)
    +ModifySaveTaskType(string name, ESaveTaskTypes type)
    +OnWindowClosing(object? sender, CancelEventArgs e)
    }
    
    class LanguageResourceViewModel {
        + static void SetLanguage(string cultureCode)
    }

        enum ESettingsActions {
        SwitchLanguageToFrench
        SwitchLanguageToEnglish
        SwitchLogTypeToJSON
        SwitchSaveTypeToXML
        EditedExtensions
    }

    ' Définition de la classe SettingsViewModel
    class SettingsViewModel {
        - List<ESettingsActions> UnsavedActions
        - List<string> NewEncryptingExtensions
        - SaveTaskManager saveTaskManager
        --
        + SettingsViewModel(SaveTaskManager saveTaskManager)
        + ExecuteAllUnsavedActions()
        + AddLanguageAction(ESettingsActions eSettingsActions)
        + SetLanguage(string cultureCode)
        + static ReloadMainWindow()
        + ShouldEnglishRadioButtonBeChecked() : bool
        + ShouldFrenchRadioButtonBeChecked() : bool
        + ShouldJSONRadioButtonBeChecked() : bool
        + ShouldXMLRadioButtonBeChecked() : bool
        + AddEncryptingExtension(string EncryptingExtension) : bool
        + RemoveEncryptingExtension(string EncryptingExtension) : bool
        + GetNewEncryptingExtensions() : List<string>
    }

    /' Relations '/
    SaveTaskViewModel o--> SaveTaskManager : "<<contains>>"
    SaveTaskViewModel --> ESaveTaskTypesExtension : "<<uses>>"
    SettingsViewModel o--> SaveTaskManager : "<<contains>>"
    SettingsViewModel --> ESettingsActions : "<<uses>>"
    SettingsViewModel --> LanguageResourceViewModel : "<<uses>>" 
    Utilities <-- SaveTaskManager : "<<uses>>"
}

package "View" {
      class MainWindow {
        + MainWindow()
        - void AddRow_Click(object sender, RoutedEventArgs e)
        - void StartSelected_Click(object sender, RoutedEventArgs e)
        - void ModifySelected_Click(object sender, RoutedEventArgs e)
        - void DeleteSelected_Click(object sender, RoutedEventArgs e)
        - void SettingsButton_Click(object sender, RoutedEventArgs e)
        - void BackupTable_CellEditEnding(object sender, DataGridCellEditEndingEventArgs e)
        - void LaunchSettingsWindow()
        - SaveTaskViewModel saveTaskViewModel
        - SaveTaskWindow saveTaskWindow
        - SaveTaskManager saveTaskManager
    }

    class SaveTaskWindow {
        + SaveTaskWindow(SaveTaskViewModel saveTaskViewModel)
        --
        - void SaveButton_Click(object sender, RoutedEventArgs e)
        - void CancelButton_Click(object sender, RoutedEventArgs e)
        - SaveTaskViewModel saveTaskViewModel
    }

        class SettingsWindow {
        + SettingsWindow(SaveTaskManager saveTaskManager)
        --
        - void FrenchLanguageRadioButton_Checked(object sender, RoutedEventArgs e)
        - void EnglishLanguageRadioButton_Checked(object sender, RoutedEventArgs e)
        - void Save_Click(object sender, RoutedEventArgs e)
        - void Cancel_Click(object sender, RoutedEventArgs e)
        - void ValidateExtensionButton(object sender, RoutedEventArgs e)
        - void RefreshEncryptingExtensionsDisplay()
        - void DeleteExtensionButton_Click(object sender, RoutedEventArgs e)
        --
        - SettingsViewModel settingsViewModel
    }

    MainWindow *--> SaveTaskManager : "<<instanciates>>"
    MainWindow *--> SaveTaskViewModel : "<<instanciates>>"
    MainWindow --> SaveTaskWindow : "<<creates>>"
    MainWindow --> SaveTask : "<<uses>>"
    SettingsWindow *--> SettingsViewModel : "<<instanciates>>"
    SaveTaskWindow o--> SaveTaskViewModel : "<<contains>>"
    SettingsViewModel ---> MainWindow : "<<reloads>>"
}

' package "LogDll" {
'     class LogDaily {
'         + dailyInfo: DailyInfo
'         + stopWatch: Stopwatch
'         + LogDaily(LogDailyPath: string, LogRealTimePath: string)
'         + CreateDailyFile(): void
'         + AddDailyInfo(SourcePath: string, TargetPath: string): void
'     }


'     class JsonLogManager {
'         + UpdateRealTimeProgression(realTimeInfo: RealTimeInfo, LogRealTimePath: string): void
'         + GetFileDailyName(Date: DateTime, LogDailyPath: string): string
'         + CreateDailyJsonFile(Date: DateTime, LogDailyPath: string): void
'         + AddSaveToDailyFile(DailyInfo: DailyInfo, LogDailyPath: string): void
'         + AddSaveToRealTimeFile(realTimeInfo: RealTimeInfo, LogRealTimePath: string): void
'         + AddJsonLogObject(FilePath: string, LogObject: object): void
'         + GetLastSaveDate(LogDailyPath: string, FilePath: string): DateTime
'     }

'     enum ERealTimeState <<enum>> {
'         ACTIVE
'         END
'         ERROR
'     }

'     class ERealTimeStateExstensions {
'         - static Dictionary<ERealTimeState, string> MessageStrings
'         + static string GetValue(ERealTimeState message)
'     }

'     struct RealTimeInfo {
'     + string Name
'     + string SourcePath
'     + string TargetPath
'     + string State
'     + int TotalFilesToCopy
'     + long TotalFilesSize
'     + int NbFilesLeftToDo
'     + double Progression
'     + DateTime SaveDate
'     + RealTimeInfo(string name, string sourceFilePath, string targetFilePath, string state, int totalFilesToCopy, long totalFilesSize, int nbFilesLeftToDo, int progression, DateTime saveDate)
'     + string ToString()
' }

'     struct DailyInfo {
'     - Name: string
'     - FileSource: string
'     - FileTarget: string
'     - FileSize: long
'     - FileTransferTime: double
'     - DateTime: DateTime
'     + ToString(): string
'     + DailyInfo(name: string, fileSource: string, fileTarget: string, fileSize: long, fileTransferTime: double, time: DateTime)
'     }

'     class LogRealTime {
'     + realTimeInfo: RealTimeInfo
'     + LogRealTime(LogDailyPath: string, LogRealTimePath: string)
'     + CreateRealTimeInfo(SourcePath: string, TargetPath: string, state: ERealTimeState)
'     + GetTotalFilesInfosToCopy(path: string): Tuple<int, int>
'     + UpdateRealTimeProgress(): void
'     }

'     abstract class Log <<abstract>> {
'         # LogRealTimePath: string
'         # LogDailyPath: string
'         # Log(LogDailyPath: string, LogRealTimePath: string)
'     }

'     LogDaily  --> JsonLogManager : "<<uses>>"
'     LogRealTime --> JsonLogManager : "<<uses>>"
'     LogDaily ..|> Log : "<<implements>>"
'     LogRealTime ..|> Log : "<<implements>>"
'     LogRealTime --> ERealTimeState : "<<uses>>"
'     ERealTimeStateExstensions --> ERealTimeState : "<<uses>>"
'     LogRealTime --> ERealTimeStateExstensions : "<<uses>>"
'     JsonLogManager --> RealTimeInfo : "<<uses>>"
'     LogRealTime --> RealTimeInfo : "<<uses>>"
'     JsonLogManager --> DailyInfo : "<<uses>>"
'     LogDaily --> DailyInfo : "<<uses>>"
'     SaveTaskDifferential --> JsonLogManager : "<<uses>>"
'     SaveTaskFactory --> LogDaily : "<<instanciates>>"
'     SaveTaskFactory --> LogRealTime : "<<instanciates>>"
'     LogDaily <--o SaveTask : "<<contains>>"
'     LogRealTime <--o SaveTask : "<<contains>>"

' }

@enduml